# Numpy
## HW
### HW. Блок Numpy. Задача 1

- Создайте переменную **array_one** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 6 строк на 11 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **list_two** и присвойте ей значение сгенерированного списка случайными значениями, состоящего из **11 элементов** (должен быть тип переменной list)
- Создайте переменную **result** и присвойте ей значение переменожения **array_one** на диагональную матрицу, созданную из списка **list_two**

In [12]:
# Ваш код
import numpy as np
import random

array_one = np.random.randint(low=-100, high=100, size=(6, 11))
print("array_one")
print(array_one)
list_two = random.sample(range(1, 50), 11)
print("\n list_two")
print(list_two)
result = array_one@np.diag(list_two)
print("\n Перемножение")
print(result)

array_one
[[ 16  37  76  81  37  40  -3  95 -17 -51 -41]
 [-32  23  72 -56  53 -22  44 -93  37  64  73]
 [-28  21  -1   1  78  -4 -73 -59 -62   3  62]
 [-51  77 -77 -59  24  83 -97   2  35  67 -72]
 [ 49 -81  77 -94  42 -64 -58  29  -7  44   2]
 [-20  83   6 -56 -69 -42 -10 -22 -53 -56  93]]

 list_two
[11, 37, 29, 6, 27, 49, 34, 41, 36, 24, 13]

 Перемножение
[[  176  1369  2204   486   999  1960  -102  3895  -612 -1224  -533]
 [ -352   851  2088  -336  1431 -1078  1496 -3813  1332  1536   949]
 [ -308   777   -29     6  2106  -196 -2482 -2419 -2232    72   806]
 [ -561  2849 -2233  -354   648  4067 -3298    82  1260  1608  -936]
 [  539 -2997  2233  -564  1134 -3136 -1972  1189  -252  1056    26]
 [ -220  3071   174  -336 -1863 -2058  -340  -902 -1908 -1344  1209]]


### HW. Блок Numpy. Задача 2

- Создайте переменную **array_two** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 8 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **array_three** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 1 столбец** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **result** и присвойте ей значение переменожения **транспонированной матрицы array_two** на матрицу **array_three**

In [11]:
# Ваш код
array_two = np.random.randint(low=-100, high=100, size=(11, 8))
print("array_two")
print(array_two)
array_three = np.random.randint(low=-100, high=100, size=(11, 1))
print("\n array_three")
print(array_three)
result = np.transpose(array_two)@array_three
print("\n Переменожение")
print(result)

array_two
[[  41  -93  -92   16  -33  -37  -65  -29]
 [ -27   -1  -75   33  -86 -100  -71  -36]
 [  40  -68  -41   62  -36   55  -29  -37]
 [  -1   90  -26  -16   -1  -76  -22   70]
 [  71  -76  -35   29   47  -12   11   11]
 [ -60   30  -37  -40  -62   43   89  -78]
 [  59  -82  -29  -95   51  -80   56   -6]
 [ -43  -59  -87   51  -49   66   64  -61]
 [  67   67   35  -89   70   95  -47  -49]
 [  77  -65    6  -84   14   88   11   99]
 [  -6  -86   72   32  -68   97  -24   71]]

 array_three
[[-33]
 [-58]
 [ 85]
 [-93]
 [-84]
 [-79]
 [-68]
 [ 45]
 [-83]
 [ 68]
 [-72]]

 Переменожение
[[-3358]
 [-7877]
 [ 2558]
 [13166]
 [-1575]
 [15900]
 [ 3338]
 [ 1978]]


### HW. Блок Numpy. Задача 3

- Создайте переменную **array_one** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 6 строк на 11 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **array_two** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 8 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **array_one_t** и присвойте ей матрицу **array_one** с измененным размером, где она будет иметь 33 строки и 2 столбца (то есть, по итогу мы должны в array_one_t получить матрицу из array_one размером (33,2))
- Создайте переменную **rang_1** и присвойте ей значение найденного ранга матрицы **array_one_t** при помощи numpy
- Создайте переменную **rang_2** и присвойте ей значение найденного ранга матрицы **array_two** при помощи numpy

In [10]:
# Ваш код

array_one = np.random.randint(low=-100, high=100, size=(6, 11))
print("array_one")
print(array_one)
array_two = np.random.randint(low=-100, high=100, size=(11, 8))
print("\n array_two")
print(array_two)
array_one_t = array_one.reshape(33,2)
print("\n array_one_t")
print(array_one_t)
rang_1 = np.linalg.matrix_rank(array_one_t)
print("\n ранг матрицы array_one_t")
print(rang_1)
rang_2 = np.linalg.matrix_rank(array_two)
print("\n ранг матрицы array_two")
print(rang_2)

array_one
[[  88   -9  -52   98   81  -44  -28   87  -36  -44  -18]
 [  67   58  -55   69   23  -81  -87   30   99  -82  -99]
 [  62 -100   38   89  -38    3   25  -14   70   64   14]
 [ -30   45   17  -69   23   78  -77   46  -96   40   70]
 [ -10   47   43  -67   49  -82   51  -80   46  -58   91]
 [ -41   42   -8   48  -90   18  -87    5   89    2   38]]

 array_two
[[  83  -14   31   24  -12  -25  -31  -84]
 [  16  -48  -74   82  -37    2   69  -53]
 [  63  -83   30   81    9 -100  -93   67]
 [  20   -4    7    5   61  -63  -22   63]
 [  76  -73  -26  -46   22   16   11  -76]
 [  84  -85   14   36  -72   28   58    3]
 [ -88   18    0  -87  -81   64   27  -37]
 [   4   89  -99  -47  -23  -14  -43   78]
 [  -5    7  -34  -73   59  -46  -45   -1]
 [  96   41   99   37   60   73  -67  -58]
 [  75  -36   47   53   18  -64   38  -18]]

 array_one_t
[[  88   -9]
 [ -52   98]
 [  81  -44]
 [ -28   87]
 [ -36  -44]
 [ -18   67]
 [  58  -55]
 [  69   23]
 [ -81  -87]
 [  30   99]
 [ -82  -99

### HW. Блок Numpy. Задача 4

- Создайте переменную **array_four** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 8 столбцов** (должен быть тип переменной numpy.ndarray)
- Получите сингулярное разложение матрицы **array_four** при помощи numpy, запишите в соответствующие переменные **U, S, Vt**, где:
    - **U** - ортогональная матрица
    - **S** - массив, числа которого используются в диагональной матрице $\Sigma$
    - **Vt** - ортогональная матрица в уже транспонированном виде (ничего транспонировать самим не нужно)
- Создайте переменную **result** и присвойте ей значение переменожения **U**, **S** и **Vt**, где от матрицы **u** необходимо взять по 8 строк и 8 столбцов (подсказка U[:8, :8]@ ....)

In [13]:
# Ваш код

array_four =  np.random.randint(low=-100, high=100, size=(11, 8))
print("array_four")
print(array_four)
U, S, Vt = np.linalg.svd(array_four)
print("\nОртогональная матрица U:")
print(U)
print("\nДиагональная матрица S:")
print(np.diag(S))
print("\nОртогональная матрица Vt:")
print(Vt)
result = U[:8, :8]@S@Vt
print("\nРезультат умножения U, S и Vt:")
print(result)




array_four
[[-82 -73 -47  31  12  49 -31   0]
 [ 29 -89  -9 -68  35  16 -10 -62]
 [-20  81  89 -18 -55 -92  62  75]
 [-87 -70  29  -6 -76  84   8  49]
 [-16  28  24 -14 -40 -59  81 -65]
 [-91  56 -72  -7 -78   4 -43  56]
 [-60  68 -73  41  54  16  23   1]
 [ 58  -5  87 -52 -70  -3 -34  -9]
 [ 74 -70  88  89 -12  13   7 -23]
 [ 31  34 -79 -80  61  18 -12  58]
 [ 17  81 -61 -25 -80 -92  71  49]]

Ортогональная матрица U:
[[ 0.24047328 -0.34464342 -0.27625426  0.11969588  0.16594982 -0.0108073
   0.11922226  0.48818337  0.0500179   0.6706856   0.01536041]
 [ 0.3164969   0.03058042  0.21542225 -0.3314657   0.52068849  0.09676925
   0.08608463  0.23891015  0.27251731 -0.29777479  0.48447226]
 [-0.50133202  0.33549191 -0.21019154  0.00788547 -0.17690317  0.56916769
  -0.02058957  0.40872596  0.19383547  0.00473863  0.17761377]
 [ 0.12216725 -0.11322378 -0.70222047 -0.20415061  0.13341121  0.30564625
   0.34364041 -0.42675359 -0.09766188 -0.12655754  0.02200651]
 [-0.20762899  0.23642723  0.0

### HW. Блок Numpy. Задача 5

- Вам дана матрица **X_matrix** ниже (скопируйте код и вставьте в code editor)
- Необходимо вычислить собственные векторы и собственные значения матрицы **X_matrix** при помощи numpy:
    - Создайте перменную **w** и присвойте ей массив с собственными значениями матрицы X_matrix (тип numpy.ndarray)
    - Создайте перменную **v** и присвойте ей матрицу с собственными векторами матрицы X_matrix (тип numpy.ndarray)
- Проверьте, что при умножении матрицы X_matrix и собственного вектора, получается тот же результат, что и при умножении собственного значения и собственного вектора, для этого:
    - Создайте переменную **check_1** и присвойте ей результат перемножения матрицы X_matrix на нулевой вектор из **v**
    - Создайте переменную **check_2** и присвойте ей результат перемножения нулевого вектора **v** на собственное значение **w** под индексом 0
    
**Подсказка:**

Получившийся результат в **check_1** должен быть равен **check_2**

In [14]:
from numpy import linalg as LA
X_matrix = np.array([[-1, -6], [2, 6]])
w, v = LA.eig(X_matrix)

check_1 = X_matrix@v[:, 0]
check_2 = w[0]*v[:, 0]
print("Собственные значения w:")
print(w)
print("\nСобственные векторы v:")
print(v)
print("\nПеремножение X_matrix на собственный вектор:")
print(check_1)
print("\nПеремножение собственного значения на собственный вектор:")
print(check_2)

Собственные значения w:
[2. 3.]

Собственные векторы v:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]

Перемножение X_matrix на собственный вектор:
[-1.78885438  0.89442719]

Перемножение собственного значения на собственный вектор:
[-1.78885438  0.89442719]


### HW. Блок Numpy. Задача 6

- Вам даны два вектора **a** и **b** ниже (скопируйте код и вставьте в code editor)
- Создайте переменную **similarity** и присвойте значение косинуса угла между векторами **a** и **b** (можно использовать scipy)
- найдите длины векторов:
    - Создайте переменную **dist_a_manh** и присвойте значение Манхэттенской нормы вектора **a**
    - Создайте переменную **dist_b_manh** и присвойте значение Манхэттенской нормы вектора **b**
    - Создайте переменную **dist_a_euclid** и присвойте значение Евклидовой нормы вектора **a**
    - Создайте переменную **dist_b_euclid** и присвойте значение Евклидовой нормы вектора **b**

In [15]:
from scipy import spatial

a = np.array([2, 4, 5])
b = np.array([1, 3, 2])

# Ваш код

similarity = 1 - spatial.distance.cosine(a, b)
dist_a_manh = np.linalg.norm(a, ord=1)
dist_b_manh = np.linalg.norm(b, ord=1)
dist_a_euclid = np.linalg.norm(a, ord=2)
dist_b_euclid = np.linalg.norm(b, ord=2)
print("Косинус угла между векторами a и b:")
print(similarity)
print("\nМанхэттенская норма вектора a:")
print(dist_a_manh)
print("\nМанхэттенская норма вектора b")
print(dist_a_manh)
print("\nЕвклидова норма вектора a")
print(dist_a_euclid)
print("\nЕвклидова норма вектора b")
print(dist_b_euclid)

Косинус угла между векторами a и b:
0.9561828874675149

Манхэттенская норма вектора a:
11.0

Манхэттенская норма вектора b
11.0

Евклидова норма вектора a
6.708203932499369

Евклидова норма вектора b
3.7416573867739413
