# Numpy
## HW
### HW. Блок Numpy. Задача 1

- Создайте переменную **array_one** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 6 строк на 11 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **list_two** и присвойте ей значение сгенерированного списка случайными значениями, состоящего из **11 элементов** (должен быть тип переменной list)
- Создайте переменную **result** и присвойте ей значение переменожения **array_one** на диагональную матрицу, созданную из списка **list_two**

In [2]:
# Ваш код
import numpy as np
import random

array_one = np.random.randint(low=-100, high=100, size=(6, 11))
print("array_one")
print(array_one)
list_two = random.sample(range(1, 50), 11)
print("\n list_two")
print(list_two)
result = array_one@np.diag(list_two)
print("\n Перемножение")
print(result)

array_one
[[ 60   5 -63  35  -4  29  32 -35 -82 -83  89]
 [ 48  60 -88   0  79  30   9  76   7 -26 -51]
 [ 59 -82  27 -17  22 -46  90  48  -2  83  39]
 [-45 -56  54  79  26 -82  19   2 -22  51 -46]
 [-71  33 -10 -48  58  63   6  55 -91 -31   3]
 [ 83 -85 -59 -95 -63  50  90   9  61 -74  76]]

 list_two
[9, 19, 20, 26, 45, 38, 44, 6, 2, 29, 35]

 Перемножение
[[  540    95 -1260   910  -180  1102  1408  -210  -164 -2407  3115]
 [  432  1140 -1760     0  3555  1140   396   456    14  -754 -1785]
 [  531 -1558   540  -442   990 -1748  3960   288    -4  2407  1365]
 [ -405 -1064  1080  2054  1170 -3116   836    12   -44  1479 -1610]
 [ -639   627  -200 -1248  2610  2394   264   330  -182  -899   105]
 [  747 -1615 -1180 -2470 -2835  1900  3960    54   122 -2146  2660]]


### HW. Блок Numpy. Задача 2

- Создайте переменную **array_two** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 8 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **array_three** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 1 столбец** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **result** и присвойте ей значение переменожения **транспонированной матрицы array_two** на матрицу **array_three**

In [ ]:
# Ваш код
array_two = np.random.randint(low=-100, high=100, size=(11, 8))
print("array_two")
print(array_two)
array_three = np.random.randint(low=-100, high=100, size=(11, 1))
print("\n array_three")
print(array_three)
result = np.transpose(array_two)@array_three
print("\n Переменожение")
print(result)

array_two
[[ -82  -66   64   19   83   70  -91   -7]
 [ -97    5   79   17  -43  -20   76  -74]
 [ -99   97   60   13   -3  -31   76  -68]
 [  46  -17   38   39   58   73  -12   -7]
 [  85  -12  -97   35   50  -42   39   86]
 [ -59  -74  -49  -99  -85   24   11   28]
 [  57   12   99   12 -100   71    9   82]
 [  79  -45  -21  -61  -99   61  -28   31]
 [ -15  -35  -64   65   64  -18   31   91]
 [ -41  -23  -72  -85  -96  -31  -79    6]
 [  65   12  -33  -32   76   69    4   59]]

 array_three
[[-96]
 [ 13]
 [-58]
 [ 93]
 [ 79]
 [ 37]
 [-50]
 [-82]
 [ -9]
 [ 42]
 [ 46]]

 Переменожение
[[ 13238]
 [ -1501]
 [-21733]
 [  -853]
 [  9852]
 [ -7341]
 [  6121]
 [  6338]]


### HW. Блок Numpy. Задача 3

- Создайте переменную **array_one** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 6 строк на 11 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **array_two** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 8 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **array_one_t** и присвойте ей матрицу **array_one** с измененным размером, где она будет иметь 33 строки и 2 столбца (то есть, по итогу мы должны в array_one_t получить матрицу из array_one размером (33,2))
- Создайте переменную **rang_1** и присвойте ей значение найденного ранга матрицы **array_one_t** при помощи numpy
- Создайте переменную **rang_2** и присвойте ей значение найденного ранга матрицы **array_two** при помощи numpy

In [ ]:
# Ваш код

array_one = np.random.randint(low=-100, high=100, size=(6, 11))
print("array_one")
print(array_one)
array_two = np.random.randint(low=-100, high=100, size=(11, 8))
print("\n array_two")
print(array_two)
array_one_t = array_one.reshape(33,2)
print("\n array_one_t")
print(array_one_t)
rang_1 = np.linalg.matrix_rank(array_one_t)
print("\n ранг матрицы array_one_t")
print(rang_1)
rang_2 = np.linalg.matrix_rank(array_two)
print("\n ранг матрицы array_two")
print(rang_2)

array_one
[[   4  -77  -37  -65   62   64   93   40  -18 -100   15]
 [  59  -34   25   53  -52  -34  -33  -60    0    5   37]
 [ -79  -76   -5   99  -29   39  -25   80  -24  -14   -4]
 [ -74   95   99   90  -96   -3  -13   -8  -35  -31  -85]
 [ -63  -21   82  -97  -98   16   67    1  -99   67    1]
 [   8   40   50  -16   35  -79   93  -64    9   87  -70]]

 array_two
[[ -13  -53   68   27   22  -58  -47  -18]
 [  54    1   54  -45   23  -26  -20  -26]
 [  57  -97  -34   92  -69   46  -56  -51]
 [  70   29  -67   40    1   63   15   -2]
 [  52    5   78  -44   73   67   46  -47]
 [ -52   65  -95   64   51   89  -40   -5]
 [ -78    4   97    8   12  -82  -11   69]
 [-100   95  -80   35    7  -45   72   57]
 [  70   55   14   59  -92   33   71   39]
 [ -95    4  -21   49  -89   63  -98   67]
 [ -78  -70  -62    3    9  -45  -75  -56]]

 array_one_t
[[   4  -77]
 [ -37  -65]
 [  62   64]
 [  93   40]
 [ -18 -100]
 [  15   59]
 [ -34   25]
 [  53  -52]
 [ -34  -33]
 [ -60    0]
 [   5   37

### HW. Блок Numpy. Задача 4

- Создайте переменную **array_four** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 8 столбцов** (должен быть тип переменной numpy.ndarray)
- Получите сингулярное разложение матрицы **array_four** при помощи numpy, запишите в соответствующие переменные **U, S, Vt**, где:
    - **U** - ортогональная матрица
    - **S** - массив, числа которого используются в диагональной матрице $\Sigma$
    - **Vt** - ортогональная матрица в уже транспонированном виде (ничего транспонировать самим не нужно)
- Создайте переменную **result** и присвойте ей значение переменожения **U**, **S** и **Vt**, где от матрицы **u** необходимо взять по 8 строк и 8 столбцов (подсказка U[:8, :8]@ ....)

In [3]:
# Ваш код

array_four =  np.random.randint(low=-100, high=100, size=(11, 8))
print("array_four")
print(array_four)
U, S, Vt = np.linalg.svd(array_four)
print("\nОртогональная матрица U:")
print(U)
print("\nДиагональная матрица S:")
print(np.diag(S))
print("\nОртогональная матрица Vt:")
print(Vt)
result = U[:8, :8]@S@Vt
print("\nРезультат умножения U, S и Vt:")
print(result)




array_four
[[-89 -30 -10  51  27  24  12 -21]
 [ 43  71  71 -49  96  75 -91 -11]
 [ 43 -25 -56   7  14  51 -80 -67]
 [-42 -34 -70  19 -77 -46 -52 -21]
 [-39  47 -65  45 -74  21  12  72]
 [ 70 -25   5  65 -84   0  71 -46]
 [ 71  53 -42  63 -50   3 -61 -43]
 [ 71 -71  74   9  98 -13 -47 -40]
 [-16 -64  89  -3  -6  46  89  -5]
 [-24  65  13  24 -33 -49 -48  96]
 [-76 -29  32 -27 -38 -39  16 -14]]

Ортогональная матрица U:
[[-0.0719457  -0.17119925 -0.01802136  0.4075918  -0.41955976 -0.66405312
   0.04086934 -0.38477363 -0.06912745  0.06109501 -0.15436837]
 [ 0.56486783  0.28735934 -0.30214823 -0.14834542 -0.25722812  0.01651134
   0.49337031  0.00727473  0.00332488 -0.28071264 -0.31037441]
 [ 0.17605189  0.34082555  0.35749542  0.32681543 -0.29203539  0.06385231
   0.03857017  0.42932967 -0.4661944   0.31879639  0.15521153]
 [-0.32122715  0.18113258  0.17956848  0.49092684  0.23595974  0.03469106
   0.26034842  0.29227181  0.38441375 -0.15158492 -0.45816329]
 [-0.42457537  0.17546708 -0.

### HW. Блок Numpy. Задача 5

- Вам дана матрица **X_matrix** ниже (скопируйте код и вставьте в code editor)
- Необходимо вычислить собственные векторы и собственные значения матрицы **X_matrix** при помощи numpy:
    - Создайте перменную **w** и присвойте ей массив с собственными значениями матрицы X_matrix (тип numpy.ndarray)
    - Создайте перменную **v** и присвойте ей матрицу с собственными векторами матрицы X_matrix (тип numpy.ndarray)
- Проверьте, что при умножении матрицы X_matrix и собственного вектора, получается тот же результат, что и при умножении собственного значения и собственного вектора, для этого:
    - Создайте переменную **check_1** и присвойте ей результат перемножения матрицы X_matrix на нулевой вектор из **v**
    - Создайте переменную **check_2** и присвойте ей результат перемножения нулевого вектора **v** на собственное значение **w** под индексом 0
    
**Подсказка:**

Получившийся результат в **check_1** должен быть равен **check_2**

In [7]:
from numpy import linalg as LA
X_matrix = np.array([[-1, -6], [2, 6]])
w, v = LA.eig(X_matrix)

check_1 = X_matrix@v[:, 0]
check_2 = w[0]*v[:, 0]
print("Собственные значения w:")
print(w)
print("\nСобственные векторы v:")
print(v)
print("\nПеремножение X_matrix на собственный вектор:")
print(check_1)
print("\nПеремножение собственного значения на собственный вектор:")
print(check_2)

Собственные значения w:
[2. 3.]

Собственные векторы v:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]

Перемножение X_matrix на собственный вектор:
[-1.78885438  0.89442719]

Перемножение собственного значения на собственный вектор:
[-1.78885438  0.89442719]


### HW. Блок Numpy. Задача 6

- Вам даны два вектора **a** и **b** ниже (скопируйте код и вставьте в code editor)
- Создайте переменную **similarity** и присвойте значение косинуса угла между векторами **a** и **b** (можно использовать scipy)
- найдите длины векторов:
    - Создайте переменную **dist_a_manh** и присвойте значение Манхэттенской нормы вектора **a**
    - Создайте переменную **dist_b_manh** и присвойте значение Манхэттенской нормы вектора **b**
    - Создайте переменную **dist_a_euclid** и присвойте значение Евклидовой нормы вектора **a**
    - Создайте переменную **dist_b_euclid** и присвойте значение Евклидовой нормы вектора **b**

In [8]:
from scipy import spatial

a = np.array([2, 4, 5])
b = np.array([1, 3, 2])

# Ваш код

similarity = 1 - spatial.distance.cosine(a, b)
dist_a_manh = np.linalg.norm(a, ord=1)
dist_b_manh = np.linalg.norm(b, ord=1)
dist_a_euclid = np.linalg.norm(a, ord=2)
dist_b_euclid = np.linalg.norm(b, ord=2)
print("Косинус угла между векторами a и b:")
print(similarity)
print("\nМанхэттенская норма вектора a:")
print(dist_a_manh)
print("\nМанхэттенская норма вектора b")
print(dist_a_manh)
print("\nЕвклидова норма вектора a")
print(dist_a_euclid)
print("\nЕвклидова норма вектора b")
print(dist_b_euclid)

Косинус угла между векторами a и b:
0.9561828874675149

Манхэттенская норма вектора a:
11.0

Манхэттенская норма вектора b
11.0

Евклидова норма вектора a
6.708203932499369

Евклидова норма вектора b
3.7416573867739413
